### ISSUE TITLE
3P keys missing

### ISSUE THREAD

**Issue by ca333** [marmarachain/marmara#1]
https://github.com/marmarachain/Marmara-v.1.0/blob/c89a240b7fb668b0a2a6427594e290c06ff73d14/src/komodo_defs.h#L263-L329

For the dPoW integration we have to replace the S3.5 keys above with the [3P keys](https://github.com/KomodoPlatform/dPoW/blob/master/iguana/3rd_party).

**Comment by ca333** [comment]
This is mandatory for dPoW integration. Please "redo" https://github.com/marmarachain/Marmara-v.1.0/pull/2 asap

**Comment by marmarachain** [comment]
> This is mandatory for dPoW integration. Please "redo" #2 asap
https://github.com/marmarachain/Marmara-v.1.0/commit/eedd63960444e88835e5d04afe58591a373b0210
