### ISSUE TITLE
could not start marmarachain

### ISSUE THREAD

**Issue by ceyhunyor** [marmarachain/marmara#23]
This issue tracker is only for technical issues related to komodod

General Komodo questions and/or support requests and are best directed to [Discord](https://komodoplatform.com/discord)

### Describe the issue
Originally I declared my issue on that link:

https://github.com/marmarachain/marmara-connector/issues/20

The later disscussion show me that the issue I opened is related with Marmarachain rather than Marmara Connector.

### The version of Komodo you were using:
Komodo Daemon version v3.0.3-beta1-4c9faaa(hf2)

### Any extra information that might be useful in the debugging process.
This includes the relevant contents of `~/.komodo/debug.log`. You can paste raw text, attach the file directly in the issue or link to the text via a pastebin type site.
Please also include any non-standard things you did during compilation (extra flags, dependency version changes etc.) if applicable.

### Do you have a backup of `~/.komodo` directory and/or take a VM snapshot?
- Backing up / making a copy of the `~/.komodo` directory might help make the problem reproducible. Please redact appropriately.
- Taking a VM snapshot is really helpful for interactively testing fixes

![Ekran Görüntüsü (282)](https://user-images.githubusercontent.com/7870844/137613478-013ba1c7-ca05-40db-88fa-8d908411912c.png)
![Ekran Görüntüsü (283)](https://user-images.githubusercontent.com/7870844/137613481-c690ea6a-2f1a-466f-be90-95336b026d0a.png)
![Ekran Görüntüsü (284)](https://user-images.githubusercontent.com/7870844/137613482-2ac878ee-ee47-4cd2-89a9-fdef61bc82c1.png)

**Comment by rumeysayilmaz** [comment]
The fetch-params bat file inside the zip directory needs to be run.
